apiVersion: v1
kind: Namespace
metadata:
  name: judge-test
---
apiVersion: v1
kind: Service
metadata:
  namespace: judge-test
  labels:
    app: judge-k8s-webhook
  name: judge-k8s-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: 1323
      protocol: "TCP"
  selector:
    app: judge-k8s-webhook
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: attestation-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /tmp/k8s-attestations
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attestation-pvc
  namespace: judge-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: judge-test
  name: judge-k8s-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-k8s-webhook
  template:
    metadata:
      labels:
        app: judge-k8s-webhook
    spec:
      containers:
        - name: judge-k8s-webhook
          image: "skaffold-dev:34751/judge-k8s"
          command:
            - "judge-k8s"
            - "serve"
          args:
            - "--cert=/run/secrets/tls/tls.crt"
            - "--key=/run/secrets/tls/tls.key"
            - "--policy=/run/witness-policy/witness-policy.json"
            - "--port=1323"
            - "--b64-public-key=/run/witness-policy/public-key.pem.b64"
            - "--attestations=/data/attestation.json"
            - "--artifactfile=/data/pods.json"
            # - "--rekor-server=http://rekor-server.default.svc.cluster.local:8077"
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
            - name: witness-policy
              mountPath: /run/witness-policy
              readOnly: true
            - name: attestation-storage
              mountPath: /data
              readOnly: true
          ports:
            - name: http
              containerPort: 1323
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls
        - name: witness-policy
          configMap:
            name: witness-policy
        - name: attestation-storage
          persistentVolumeClaim:
            claimName: attestation-pvc
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  namespace: judge-test
  name: judge-k8s-webook
webhooks:
  - name: judge-k8s-webhook.judge-test.svc
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    failurePolicy: Ignore
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVR2hPTUN2NW90U3RSUFR1VytmbCt4WXBzYTA0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSTFNVEV4TVRFeE1ESTBNbG9YRFRJMU1USXhNVEV4TURJME1sb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTYrczFWZmhNcGhWVzFpeEhORFI0bVcwVHBPYjRLYjd6a0JjaApkZ3c5WlNSOUhpamlvUGJzVy9hdXZMbHVsanlrdklPa0FQMStUMnJzMW1odENUNkI0S1hJSWVFM1NhVkxNNkFMCjF1Qi9iTk5IS3FubUhCblhybUdRb2kvcWw1TFIvMWFpOEZSdFZzT01rc0hSSmtyaXhkbzZzcVE3UGNDVGQ2UkwKVDF5TGFEVXhzVGYrYTJ6WEFGVEJyUEMzbmFNQWRiZWd5ME4ramJZbHVaVkovR3hpSmprei9zbURuOXpGZ3VuRwoxdzVyejFOMzQ4NURJaXYrZWVGRllOU3UvenpYMkYzQTViUUppL3dkWHNLTGl0eTAyR3VzQVU3S2Vkc2pFODk4CmtxcEVIYnBqQ2xENzRCd1l1Y2JTT0lJZHlNVllYMHJ6VVlQeFgzNkwySVFJdVRKZmNRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVbU50NTExT2lBZEpWSWVzTFFSNHF0UVF3aVUwd0h3WURWUjBqQkJnd0ZvQVVtTnQ1MTFPaQpBZEpWSWVzTFFSNHF0UVF3aVUwd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFuZC9rMExFOGMrQTFORkZCWi90dFY5U1MxSlBVWThWc0pNUmkveTRUMnkwRVVzUEpZNzRDWENMY2FJL3gKUTdscHpEblhxQzYwYlRBdHpvQ3M5TTM4NE5MalFxTXNVL3ZWMFc3Mzhxb0wvekpEdUxzVnpoeTk3Kys0NTNEQQppUFFCakNZTEo0aDdZUFFGTFdPK0FiNXp4VnpSSDJzWHVxTGQyek9ZWlZ0YUF4U3dURkZ2dDZYaG9JTWR4MkRyClFza3dpZTlXNC9rZXVacC8vay9tUEFEVW9Ta0IzblB0RnFWMDdZdjZObmV6SExjSUszaEl5blcrTTY0Z0tSSk4KeGcvZi9JMXdvbWRWcTZ2TVJyWHJFUEcvWHg5eThvMm5TWXRlM0w4aFpmWWxvVVAvYnZuTFY3S0NpSS92L2dvVApDNXpXWWNRMWt1L2tLZlFZVTdCYXNkOXNUdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: judge-k8s-webhook
        namespace: judge-test
        path: /mutate
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: judge-test
  name: witness-policy
data:
  witness-policy.json: |
    {"payload":"ewogICJleHBpcmVzIjogIjIwMjctMTItMTdUMjM6NTc6NDAtMDU6MDAiLAogICJzdGVwcyI6IHsKICAgICJidWlsZCI6IHsKICAgICAgIm5hbWUiOiAiYnVpbGQiLAogICAgICAiYXR0ZXN0YXRpb25zIjogWwogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy5kZXYvYXR0ZXN0YXRpb25zL21hdGVyaWFsL3YwLjEiLAogICAgICAgICAgInJlZ29wb2xpY2llcyI6IFtdCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAidHlwZSI6ICJodHRwczovL3dpdG5lc3MuZGV2L2F0dGVzdGF0aW9ucy9jb21tYW5kLXJ1bi92MC4xIiwKICAgICAgICAgICJyZWdvcG9saWNpZXMiOiBbXQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgInR5cGUiOiAiaHR0cHM6Ly93aXRuZXNzLmRldi9hdHRlc3RhdGlvbnMvcHJvZHVjdC92MC4xIiwKICAgICAgICAgICJyZWdvcG9saWNpZXMiOiBbXQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgInR5cGUiOiAiaHR0cHM6Ly93aXRuZXNzLmRldi9hdHRlc3RhdGlvbnMvazhzbWFuaWZlc3QvdjAuMiIsCiAgICAgICAgICAicmVnb3BvbGljaWVzIjogW10KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJmdW5jdGlvbmFyaWVzIjogWwogICAgICAgIHsKICAgICAgICAgICJwdWJsaWNrZXlpZCI6ICI2YjkzOTEzZDNmNDcyMjVmZDMyNTI0Y2U3OGIyMDY0Y2ZiNmZmMjY3NWYwMzZjMDZkNDI5MjU4MjgwMDlkOThhIgogICAgICAgIH0KICAgICAgXQogICAgfQogIH0sCiAgInB1YmxpY2tleXMiOiB7CiAgICAiNmI5MzkxM2QzZjQ3MjI1ZmQzMjUyNGNlNzhiMjA2NGNmYjZmZjI2NzVmMDM2YzA2ZDQyOTI1ODI4MDA5ZDk4YSI6IHsKICAgICAgImtleWlkIjogIjZiOTM5MTNkM2Y0NzIyNWZkMzI1MjRjZTc4YjIwNjRjZmI2ZmYyNjc1ZjAzNmMwNmQ0MjkyNTgyODAwOWQ5OGEiLAogICAgICAia2V5IjogIkxTMHRMUzFDUlVkSlRpQlFWVUpNU1VNZ1MwVlpMUzB0TFMwS1RVTnZkMEpSV1VSTE1sWjNRWGxGUVcxbFYzTldjazV3U0M5V05VTjBjMFpOUlVWak5DOXpVMmxhWVZkVVVDdHdRVVZJUjFCT1RUbDNSMFU5Q2kwdExTMHRSVTVFSUZCVlFreEpReUJMUlZrdExTMHRMUW89IgogICAgfQogIH0KfQo=","payloadType":"https://witness.testifysec.com/policy/v0.1","signatures":[{"keyid":"6b93913d3f47225fd32524ce78b2064cfb6ff2675f036c06d42925828009d98a","sig":"hhHXdNII3MH3shDsm7XPBSehEnF+65roJe6VzwpoTiYj6SMYlgFB+ONEoVW6m1byPlP/ektbXfb8W3RNuDJLDQ=="}]}
  public-key.pem.b64: |
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQW1lV3NWck5wSC9WNUN0c0ZNRUVjNC9zU2laYVdUUCtwQUVIR1BOTTl3R0U9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
