apiVersion: v1
kind: Namespace
metadata:
  name: judge-test
---
apiVersion: v1
kind: Service
metadata:
  namespace: judge-test
  labels:
    app: judge-k8s-webhook
  name: judge-k8s-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: 1323
      protocol: "TCP"
  selector:
    app: judge-k8s-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: judge-test
  name: judge-k8s-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-k8s-webhook
  template:
    metadata:
      labels:
        app: judge-k8s-webhook
    spec:
      containers:
        - name: judge-k8s-webhook
          image: "skaffold-dev:34751/judge-k8s"
          command:
            - "judge-k8s"
            - "serve"
          args:
            - "--cert=/run/secrets/tls/tls.crt"
            - "--key=/run/secrets/tls/tls.key"
            - "--policy=/run/witness-policy/witness-policy.json"
            - "--port=1323"
            - "--b64-public-key=/run/witness-policy/public-key.pem.b64"
            # - "--rekor-server=http://rekor-server.default.svc.cluster.local:8077"
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
            - name: witness-policy
              mountPath: /run/witness-policy
              readOnly: true
          ports:
            - name: http
              containerPort: 1323
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls
        - name: witness-policy
          configMap:
            name: witness-policy
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  namespace: judge-test
  name: judge-k8s-webook
webhooks:
  - name: judge-k8s-webhook.judge-test.svc
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    failurePolicy: Ignore
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVTlZxR2s0UjVuL21yWU9RVEJGbnhrN2ZRbGdNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSTFNVEV4TVRBMk5EQXdORm9YRFRJMU1USXhNVEEyTkRBd05Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTB5WUIzTlY1YUFpemFCZFFUbFNXaGtoNENJYXNKVVV3Z0pBMgpHWDJDZlRWWHk2L0hsNSt6SnNZc3piNFN3dWN5RFJMejZxUU04TUVydHN5SklTZktoTHdiOWE3bEdMNUtPcFFwCkErK0xrWGtCd3N4ekpoK01KSjh3bVpod0d3c0liQ1hXaEk3U25HNU1ZSWxSR3RDKzlTMnhBOHBjb05XbUs3U04KSFc2UlF4Z3RkK05YQnNoQWNqT2JuclZKalJHOWx1MlVHaUJnTGx5WnRYNEIzc0ZoSHBLdTBlcXlxN1JmTkp6ZQp6bjMrRGlwV0J3ZmNPcXNjQ1RXWWtpNnRKbER4TXNPbFQ4ZmdDVk4ya2ZoZjNBOEQxUTRxeGtzWmE3QXAwTnkzCm5NTWpPcDJ3amdjN0RzN1VZMjR3dHY2cXpDNzJRNk1jQ2poMlp6K3hpUlpRM1ROREFRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVMVJjT2poTmwxMWhVRWFFbjRvMnpTUFVTK1A0d0h3WURWUjBqQkJnd0ZvQVUxUmNPamhObAoxMWhVRWFFbjRvMnpTUFVTK1A0d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFpS3VhdGFmdTZiQWZKbDY2V2R4S2J2RmlxQzlNU2l1OTd4b3plajF2Nm9LMVhPODNOU08wTG5iRE5IS2YKMjRka1lyVFVaYTc2UFEyK3JvYnlld2RJUGo3Z29ucU1vMkprdnFTUUdpeVM2VG01YytUTDJxSnFlZFNYVVMwZgo2YkF6WjUzamhFNFlTTDAvWWZ1V1JmTnhTK2NaKzNQVUl1bklaSUljZlNROFRXK3dSNGEzK2wxc3ZicFg3VHNNCnFWdnpPTTJta01hcUpqQ3NMdlliWndKVzR6RFRQTjg4SGlTMGVBNUo2YjZva1NyY2pBU0dHSU1OVkRuOFMvUTMKcmZZNUVDRDRxRkZFQW1uK0c0QWZwSldIMklCTFR1NmNtUEVpd2Rwa0o5TW0rdGdmVkdHSTIxelBkR3VFbW1OQQp5NlpEQ3R0N2lhODhDUlJWLzJLZVZHNlB4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: judge-k8s-webhook
        namespace: judge-test
        path: /mutate
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: judge-test
  name: witness-policy
data:
  witness-policy.json: |
    {"payload":"ewogICJleHBpcmVzIjogIjIwMjctMTItMTdUMjM6NTc6NDAtMDU6MDAiLAogICJzdGVwcyI6IHsKICAgICJidWlsZCI6IHsKICAgICAgIm5hbWUiOiAiYnVpbGQiLAogICAgICAiYXR0ZXN0YXRpb25zIjogWwogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy5kZXYvYXR0ZXN0YXRpb25zL21hdGVyaWFsL3YwLjEiLAogICAgICAgICAgInJlZ29wb2xpY2llcyI6IFtdCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAidHlwZSI6ICJodHRwczovL3dpdG5lc3MuZGV2L2F0dGVzdGF0aW9ucy9jb21tYW5kLXJ1bi92MC4xIiwKICAgICAgICAgICJyZWdvcG9saWNpZXMiOiBbXQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgInR5cGUiOiAiaHR0cHM6Ly93aXRuZXNzLmRldi9hdHRlc3RhdGlvbnMvcHJvZHVjdC92MC4xIiwKICAgICAgICAgICJyZWdvcG9saWNpZXMiOiBbXQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgInR5cGUiOiAiaHR0cHM6Ly93aXRuZXNzLmRldi9hdHRlc3RhdGlvbnMvazhzbWFuaWZlc3QvdjAuMiIsCiAgICAgICAgICAicmVnb3BvbGljaWVzIjogW10KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJmdW5jdGlvbmFyaWVzIjogWwogICAgICAgIHsKICAgICAgICAgICJwdWJsaWNrZXlpZCI6ICI0MDNiMDA4MjIxNjNkMDk2NTBjMDczYjJmMzIyYWU5OWNkNmFhYTcyOTBkNGJjMzUzNDM4NzYxN2M1ODNlMDRkIgogICAgICAgIH0KICAgICAgXQogICAgfQogIH0sCiAgInB1YmxpY2tleXMiOiB7CiAgICAiNDAzYjAwODIyMTYzZDA5NjUwYzA3M2IyZjMyMmFlOTljZDZhYWE3MjkwZDRiYzM1MzQzODc2MTdjNTgzZTA0ZCI6IHsKICAgICAgImtleWlkIjogIjQwM2IwMDgyMjE2M2QwOTY1MGMwNzNiMmYzMjJhZTk5Y2Q2YWFhNzI5MGQ0YmMzNTM0Mzg3NjE3YzU4M2UwNGQiLAogICAgICAia2V5IjogIkxTMHRMUzFDUlVkSlRpQlFWVUpNU1VNZ1MwVlpMUzB0TFMwS1RVTnZkMEpSV1VSTE1sWjNRWGxGUVRSUmMwOTZlRVpWYUhKRVpUSmFNV2hzVUhkck1XdHNSbmQzU201M2IwVmpRbTFaTURsVk1UUk5PVGc5Q2kwdExTMHRSVTVFSUZCVlFreEpReUJMUlZrdExTMHRMUW89IgogICAgfQogIH0KfQo=","payloadType":"https://witness.testifysec.com/policy/v0.1","signatures":[{"keyid":"403b00822163d09650c073b2f322ae99cd6aaa7290d4bc3534387617c583e04d","sig":"fUkGS7QU6r7lZ8GiqRo7pAU4/VbMSwVUJXZDz7bmWwA0gZO0hXS5/sYLKijzJO3Tsm2E6n1aAZAiIQE89WKXBQ=="}]}
  public-key.pem.b64: |
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQTRRc096eEZVaHJEZTJaMWhsUHdrMWtsRnd3Sm53b0VjQm1ZMDlVMTRNOTg9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
